[package]
name = "project_api_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
fuser="0.16.0"
tokio={version="1.0", features = ["full"]}
serde={version = "1.0", features = ["derive"]}
reqwest={version = "0.12.23", features = ["json"]}
clap="4.0"
tracing="0.1"